name: Build 4get

on:
  push:
    branches: ["master"]
  workflow_dispatch:
    inputs:
      cache:
        description: "Use cache if available"
        required: false
        default: true
        type: boolean

jobs:
  build:
    runs-on: [ubuntu-latest, amd64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install cosign
        uses: sigstore/cosign-installer@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Set Lowercase Repository Name
        run: echo "lowercase=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Login
        run: echo "${{ secrets.TOKEN }}" | docker login ${{ vars.REGISTRY }} -u ${{ github.actor }} --password-stdin

      - name: Build
        run: |
          if [ "${{ inputs.cache }}" = "0" ]; then
            docker build --no-cache -t ${{ env.lowercase }}:latest .
          else
            docker build -t ${{ env.lowercase }}:latest .
          fi

      - name: Tag
        run: docker tag ${{ env.lowercase }}:latest ${{ vars.REGISTRY }}/${{ env.lowercase }}:latest

      - name: Push
        run: docker push ${{ vars.REGISTRY }}/${{ env.lowercase }}:latest

      - name: Cleanup
        continue-on-error: true
        run: docker images -f "dangling=true" -q | xargs -r docker rmi